### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Nukesor** [Nukesor/pueue-rs#2]
- [x] add
- [x] remove
- [x] start
- [x] pause
- [x] kill (Forcefully stop commands)
- [x] status
- [x] log (Show output of finished processes) 
- [x] show (Show the output of a running process, eventually with -f flag)
- [x] edit (Edit a command that has not started yet) (Stash and unstash during editing)
- [x] switch (Switch the places of two tasks)
- [x] send (Send input to a process)
- [x] reset (Kill all commands and reset everything to a fresh start)
- [x] clean (Remove all finished tasks from the list)
- [x] restart (Clone and queue a finished task)
- [x] stash (Stash a task for later execution. Won't be started until enqueued)
- [x] enqueue (Enqueue a stashed task for normal execution)

- [x] Make Settings adjustable during runtime
- [x] Log rotating
- [x] Serialize and save state. (Load state on restart)
- [ ] Some kind of security (probably shared secret)
